# Generated by Django 4.2.5 on 2023-11-22 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_student_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='interested_students',
            field=models.ManyToManyField(blank=True, related_name='interested_courses', to='myapp.student'),
        ),
    ]
